# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
SECRET_KEY_BASE: c40744fa09b911bc9af6ad8e28d8e2a17208b87a9ed1f47d0b961c60c6b67e61f0072081eee3dd801681e5031bbc90a6159f223303e5b3b54918442ff0a3959b
AWS_ACCES_KEY_ID: AKIAIRPKLJNSDO23425
AWS_SECRET_ACCESS_KEY: 9LXV/GWagu/CJ4DoMLKSmdasdaZeUyuax/Ei92hL7
EMAIL_LOGIN: jobboardbox@gmail.com
EMAIL_PASSWORD: testjobboard

development:
  FOG_DIRECTORY: job-board-app-dev
production:
  FOG_DIRECTORY: job-board-app-production
